system:
  paths:
    install: /opt/reppy
    logging: ..
    current: files/jobs/current
    upload: files/upload
    unpack: files/unpack
  filetypes:
    allowed: [zip]
  modules:
    api: enabled
    wsc: enabled
  wsc:
    bind: 0.0.0.0
    port: 8765

print:
  layer:
    default:
      speed: 5 # mm/s TODO
      height: 5 # mm TODO
      blackout: 10 # ms
      exposure: 6500 # ms
    bottom:
      speed: 5 # mm/s TODO
      height: 5 # mm TODO
      layers: 10 # layers
      blackout: 10 # ms
      exposure: 10000 # ms
  acceleration:
    min_delay: 1 # ms TODO
    max_delay: 100 # ms TODO
  resin:
    settling: 100 # ms

machine:
  name: Wanhao Duplicator D8
  dimensions:
    x: 192 # width in mm
    y: 120 # length in mm
    z: 180 # height in mm
  accuracy:
    x: 0.075 # 75µm
    y: 0.075 # 75µm
    z: 0.010 # 10µm
  resolution:
    x: 2560 # px
    y: 1600 # px
  hdmi_port: 0
gpio:
  motor_stepping: # not used at the moment
    pin: 24 # TODO
    mode: OUT
  motor_direction:
    pin: 1 # TODO
    mode: OUT
  motor_disabled:
    pin: 2 # TODO
    mode: OUT
  limit_switch:
    pin: 3
    mode: IN
    level: UP # TODO
  uv_enabled:
    pin: 23 # TODO
    mode: OUT
