system:
  paths:
    install: /opt/reppy
    logging: ..
    current: files/jobs/current
    upload: files/upload
    unpack: files/unpack
  filetypes:
    allowed: [zip]
  modules:
    api: enabled
    wsc: enabled
  wsc:
    bind: 0.0.0.0
    port: 8765

print:
  layer:
    default:
      speed: 5 # mm/s
      height: 5 # mm
      blackout: 0.01 # s
      exposure: 6.5 # s
    bottom:
      speed: 5 # mm/s
      height: 5 # mm
      layers: 10 # layers
      blackout: 0.01 # s
      exposure: 10 # s
  acceleration:
    min_delay: 0.001 # s
    max_delay: 0.1 # s
  resin:
    settling: 100 # ms

machine:
  name: Wanhao Duplicator D8
  dimensions:
    x: 192 # width in mm
    y: 120 # length in mm
    z: 180 # height in mm
  accuracy:
    x: 0.075 # 75µm
    y: 0.075 # 75µm
    z: 0.010 # 10µm
  resolution:
    x: 2560 # px
    y: 1600 # px
  hdmi_port: 0
  stepping: 16
gpio:
  motor_stepping: # not used at the moment
    pin: 24
    mode: OUT
  motor_direction:
    pin: 1
    mode: OUT
  motor_disabled:
    pin: 2
    mode: OUT
  limit_switch:
    pin: 3
    mode: IN
    level: UP
  uv_enabled:
    pin: 23
    mode: OUT
