system:
  type: dict
  schema:
    paths:
      type: dict
      schema:
        upload:
          type: string
        unpack:
          type: string
        current:
          type: string

print:
  type: dict
  schema:
    layer:
      type: dict
      schema:
        default:
          type: dict
          schema:
            speed:
              type: float
              min: 0   # Replace with the desired minimum speed
              max: 100
            height:
              type: float
              min: 0
            blackout:
              type: integer
              min: 0
            exposure:
              type: integer
              min: 0
        bottom:
          type: dict
          schema:
            speed:
              type: float
              min: 0   # Replace with the desired minimum speed
              max: 100
            height:
              type: float
              min: 0
            layers:
              type: integer
              min: 0
            blackout:
              type: integer
              min: 0
            exposure:
              type: integer
              min: 0
    retraction:
      type: dict
      schema:
        speed:
          type: float
          min: 0
          max: 100 # Replace with the desired maximum speed
        height:
          type: float
          min: 0
    acceleration:
      type: dict
      schema:
        min_delay:
          type: integer
          min: 0
        max_delay:
          type: integer
          min: 0
    resin:
      type: dict
      schema:
        settling:
          type: float
          min: 0   # Replace with the desired minimum speed

machine:
  type: dict
  schema:
    name:
      type: string
    dimensions:
      type: dict
      schema:
        x:
          type: integer
          min: 0
        y:
          type: integer
          min: 0
        z:
          type: integer
          min: 0
    accuracy:
      type: dict
      schema:
        x:
          type: float
          min: 0
        y:
          type: float
          min: 0
        z:
          type: float
          min: 0
    resolution:
      type: dict
      schema:
        x:
          type: integer
          min: 0
        y:
          type: integer
          min: 0

gpio:
  type: dict
  schema:
    motor_stepping:
      type: dict
      schema:
        pin:
          type: any
          allowed: [false, true]
        mode:
          type: string
          allowed: ["IN", "OUT"]
    motor_direction:
      type: dict
      schema:
        pin:
          type: integer
          min: 0
        mode:
          type: string
          allowed: ["IN", "OUT"]
    motor_enabled:
      type: dict
      schema:
        pin:
          type: integer
          min: 0
        mode:
          type: string
          allowed: ["IN", "OUT"]
    limit_switch:
      type: dict
      schema:
        pin:
          type: integer
          min: 0
        mode:
          type: string
          allowed: ["IN", "OUT"]
        level:
          type: string
          allowed: ["UP", "DOWN"]
    led_switch:
      type: dict
      schema:
        pin:
          type: integer
          min: 0
        mode:
          type: string
          allowed: ["IN", "OUT"]
